config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :notes
  authenticated :user do
    root "notes#index", as: "authenticated_root"
  end

  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  validates :title, presence: true, length: { minimum:15 }
  validates :content, presence: true, length: { minimum:350, maximum:12000 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  def index
    @notes = Note.where(user_id: current_user)
  end

  def show
  end

  def new
    @note = current_user.notes.build
  end

  def create
    @note = current_user.notes.build(note_params)
     if @note.save
       redirect_to @note, notice: 'created.'
     else
       render 'new', notice: 'Something went wrong, please try again.'
     end
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to @note, notice: 'Updated'
    else
      redirect_to 'edit', notice: 'Something went wrong, please try again.'
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_path
  end

  private

   def find_doc
     @note = Note.find(params[:id])
   end

   def note_params
     params.require(:note).permit(:title, :content)
   end

   def check_user
      if current_user.id != @note.user_id
        redirect_to root_url, alert: "You are not authorized to destroy this listing"
      end
   end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.erb
<%= simple_form_for @doc do |f| %>
  <%= f.input :title, class: "form-control "%>
  <%= f.input :content, class: "form-control", placeholder: ""%>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/docs/edit.html.erb
<h3> Fix Document </h3>
<%= render 'form' %>
<%= link_to 'Cancle', docs_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" >
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">quick-note</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right font-style-condensed">
        <% if user_signed_in? %>
            <li class = "content-form"><%= link_to "+New Note", new_note_path %></li>
            <li class = "content-form"><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li class = "content-form"><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li class = "content-form"><%= link_to "Create New Account", new_user_registration_path %></li>
            <li class = "content-form"><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>quick-note</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Amaranth|Raleway|Roboto" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class = "container">
        <p class="notice "alert""><%= notice %><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<%= simple_form_for @note do |f| %>
  <%= f.input :title, class: "form-control "%>
  <%= f.input :content, class: "form-control" %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/notes/edit.html.erb
<h3>Edit Note </h3>
<%= render 'form' %>
<%= link_to 'Cancle', notes_path %>

app/views/notes/index.html.erb
<% @notes.each do |note| %>
  <div class = "jumbotron">
    <h3 class = "heading-font"><b><%= note.title %></b></h3><hr>
     <p><h6 class = "date-description content-font">
      <%= time_ago_in_words(note.created_at) %> ago <br/><br/>
     </p></h6>
     <p><h5 class = "content-font">
      <%= truncate(note.content, length:250) %>..<%=%> <%= link_to "read more", note %>
    </h5></p><hr>
  </div><br>
<% end %>

app/views/notes/new.html.erb
<h1> New Note </h1>

<%= render 'form' %>

app/views/notes/show.html.erb
<div class = "jumbotron">
 <h3 class = "heading-font" ><b><%= @note.title %></b></h3><hr>
  <p><h6 class = "date-description content-font"> <%= time_ago_in_words(@note.created_at) %> ago </p>
   <h5 class = "content-font"><%= @note.content %><h4>
     <p><br>
      <h6 class = "content-font">
      <% if (user_signed_in?) && (current_user.id == @note.user_id) %>
        <%= link_to "Back", "/" %>|
        <%= link_to "Edit", edit_note_path(@note) %>|
        <%= link_to "Delete", note_path(@note), method: :delete, data: { confirm: "Are you sure?" } %>
      <% end %>
    </h5>
  </p>
</div>

app/views/welcome/index.html.erb
<center>
  <h1 class = "welcome">
     Beautiful App designed for note taking.
  </h1>
</center>